server:
  port: 7075

spring:
  application:
    name: ms-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/markmercado1/EventsProyect.git
          searchPaths:
            - config-data
          default-label: test

  security:
    user:
      name: root
      password: 123456
